// arat

		  shop_manager.cpp shopEx.cpp item_manager_read_tables.cpp shutdown_manager.cpp\

// altına ekleyin

ENABLE_MOUNT_COSTUME_SYSTEM = 1
ifeq ($(ENABLE_MOUNT_COSTUME_SYSTEM), 1)
CPPFILE += MountSystem.cpp
endif