#ifndef __INC_METIN_II_LENGTH_H__
#define __INC_METIN_II_LENGTH_H__

#include "service.h"

#define WORD_MAX 0xffff
enum EMisc
{
	MAX_HOST_LENGTH			= 15,
	IP_ADDRESS_LENGTH		= 15,
	LOGIN_MAX_LEN			= 30,
	PASSWD_MAX_LEN			= 16,
	// PIN_MAX_NUM = 6,
	PLAYER_PER_ACCOUNT		= 5,
	ACCOUNT_STATUS_MAX_LEN	= 8,
	CHARACTER_NAME_MAX_LEN	= 24,
	SHOP_SIGN_MAX_LEN		= 32,

	ABILITY_MAX_NUM			= 50,
	EMPIRE_MAX_NUM			= 4,
	BANWORD_MAX_LEN			= 24,
	SMS_MAX_LEN				= 80,
	MOBILE_MAX_LEN			= 32,
	SOCIAL_ID_MAX_LEN		= 18,

	GUILD_NAME_MAX_LEN		= 12,

	SHOP_HOST_ITEM_MAX_NUM	= 100,	/* 호스트의 최대 아이템 개수 */
	SHOP_GUEST_ITEM_MAX_NUM = 18,	/* 게스트의 최대 아이템 개수 */

	SHOP_PRICELIST_MAX_NUM	= 100,	///< 개인상점 가격정보 리스트에서 유지할 가격정보의 최대 갯수

	CHAT_MAX_LEN			= 512,

	QUICKSLOT_MAX_NUM		= 36,

	JOURNAL_MAX_NUM			= 2,

	QUERY_MAX_LEN			= 8192,

	FILE_MAX_LEN			= 128,

	PLAYER_EXP_TABLE_MAX	= 250,
	PLAYER_MAX_LEVEL_CONST	= 250,

	GUILD_MAX_LEVEL			= 20,
	MOB_MAX_LEVEL			= 100,

	ATTRIBUTE_MAX_VALUE		= 20,
	CHARACTER_PATH_MAX_NUM	= 64,
	SKILL_MAX_NUM			= 255,
	SKILLBOOK_DELAY_MIN		= 64800,
	SKILLBOOK_DELAY_MAX		= 108000, 
#ifdef S_SKILL
	SKILL_MAX_LEVEL			= 50,
#else
	SKILL_MAX_LEVEL			= 40,
#endif

	APPLY_NAME_MAX_LEN		= 32,
	EVENT_FLAG_NAME_MAX_LEN = 32,

	MOB_SKILL_MAX_NUM		= 5,

    POINT_MAX_NUM = 255,
	DRAGON_SOUL_BOX_SIZE = 32,
	DRAGON_SOUL_BOX_COLUMN_NUM = 8,
	DRAGON_SOUL_BOX_ROW_NUM = DRAGON_SOUL_BOX_SIZE / DRAGON_SOUL_BOX_COLUMN_NUM,
	DRAGON_SOUL_REFINE_GRID_SIZE = 15,
	MAX_AMOUNT_OF_MALL_BONUS	= 20,

	// WEAR_MAX_NUM				= 32,
#ifdef THANOS_GLOVE
	WEAR_MAX_NUM = 36,
#else
	WEAR_MAX_NUM = 32,
#endif

	//LIMIT_GOLD
	GOLD_MAX = 2000000001,
	#ifdef ENABLE_CHEQUE_SYSTEM
	CHEQUE_MAX = 1000,
	#endif
#ifdef ENABLE_FISH_EVENT
	FISH_EVENT_SLOTS_NUM 		= 24,
	ITEM_FISH_EVENT_BOX			= 25106,
	ITEM_FISH_EVENT_BOX_SPECIAL	= 25107,
#endif
	#ifdef __GAYA_SYSTEM__
	GAYA_MAX = 1000000,
	#endif
	#ifdef ENABLE_REBIRT_SYSTEM
	REBIRT_MAX = 10,
	#endif
	//END_LIMIT_GOLD

	SHOP_TAB_NAME_MAX = 32,
	SHOP_TAB_COUNT_MAX = 3,

	INVENTORY_PAGE_SIZE		= 45,
	INVENTORY_PAGE_COUNT	= 4,
	INVENTORY_MAX_NUM = INVENTORY_PAGE_SIZE * INVENTORY_PAGE_COUNT,

	BELT_INVENTORY_SLOT_WIDTH = 4,
	BELT_INVENTORY_SLOT_HEIGHT= 4,
	BELT_INVENTORY_SLOT_COUNT = BELT_INVENTORY_SLOT_WIDTH * BELT_INVENTORY_SLOT_HEIGHT,

	#ifdef ENABLE_SPECIAL_STORAGE
	SPECIAL_INVENTORY_PAGE_COUNT = 4,
	SPECIAL_INVENTORY_PAGE_SIZE = 45,
	SPECIAL_INVENTORY_MAX_NUM = SPECIAL_INVENTORY_PAGE_SIZE * SPECIAL_INVENTORY_PAGE_COUNT,
	#endif

	#ifdef ENABLE_BEVIS_CHECK_CLIENT_VERSION_SERVER_AND_PIN
	PIN_MAX_NUM = 6,
	#endif

#ifdef ENABLE_GEM_SYSTEM
	GEM_SLOTS_MAX_NUM = 27,
	GEM_REFRESH_ITEM_VNUM = 39063,
	GEM_UNLOCK_ITEM_VNUM = 39064,
	GEM_GLIMMERSTONE_VNUM = 50926,
	GEM_REFRESH_PULSE = 5, //hours
	GEM_MAX = 1000000,
#endif
/**
	 **** 현재까지 할당 된 아이템 영역 정리 (DB상 Item Position) ****
	+------------------------------------------------------+ 0
	| 캐릭터 기본 인벤토리 (45칸 * 2페이지) 90칸           | 
	+------------------------------------------------------+ 90 = INVENTORY_MAX_NUM(90)
	| 캐릭터 장비 창 (착용중인 아이템) 32칸                |
	+------------------------------------------------------+ 122 = INVENTORY_MAX_NUM(90) + WEAR_MAX_NUM(32)
	| 용혼석 장비 창 (착용중인 용혼석) 12칸                | 
	+------------------------------------------------------+ 134 = 122 + DS_SLOT_MAX(6) * DRAGON_SOUL_DECK_MAX_NUM(2)
	| 용혼석 장비 창 예약 (아직 미사용) 18칸               | 
	+------------------------------------------------------+ 152 = 134 + DS_SLOT_MAX(6) * DRAGON_SOUL_DECK_RESERVED_MAX_NUM(3)
	| 벨트 인벤토리 (벨트 착용시에만 벨트 레벨에 따라 활성)|
	+------------------------------------------------------+ 168 = 152 + BELT_INVENTORY_SLOT_COUNT(16) = INVENTORY_AND_EQUIP_CELL_MAX
	| 미사용                                               |
	+------------------------------------------------------+ ??
*/
};

#ifdef WJ_CHANGELOOK_SYSTEM
enum EChangeLookInfo
{
	CL_WINDOW_MAX_MATERIALS = 3,
	CL_CLEAN_ATTR_VALUE0 = 8,
	CL_TRANSMUTATION_PRICE = 50000000,
	CL_SCROLL_VNUM = 72326,
};
#endif

#ifdef ENABLE_SWITCHBOT
enum SwitchbotValues
{
	SWITCHBOT_SLOT_COUNT = 5,
	SWITCHBOT_ALTERNATIVE_COUNT = 2,
	//1 = Switching Item
	//2 = Yang
	SWITCHBOT_PRICE_TYPE = 1,
	//Amount Swtichting Items the Yang-Price
	SWITCHBOT_PRICE_AMOUNT = 1,
};

const DWORD c_arSwitchingItems[5] =
{
	39028,
	71084,
	76014,
	71151,
	76023,
};
#endif

enum EWearPositions
{
	WEAR_BODY,			// 0
	WEAR_HEAD,			// 1
	WEAR_FOOTS,			// 2
	WEAR_WRIST,			// 3
	WEAR_WEAPON,		// 4
	WEAR_NECK,			// 5
	WEAR_EAR,			// 6
	WEAR_UNIQUE1,		// 7
	WEAR_UNIQUE2,		// 8
	WEAR_ARROW,			// 9
	WEAR_SHIELD,		// 10
	WEAR_ABILITY1,		// 11
	WEAR_ABILITY2,		// 12
	WEAR_ABILITY3,		// 13
	WEAR_ABILITY4,		// 14
	WEAR_ABILITY5,		// 15
	WEAR_ABILITY6,		// 16
	WEAR_ABILITY7,		// 17
	WEAR_ABILITY8,		// 18
	WEAR_COSTUME_BODY,	// 19
	WEAR_COSTUME_HAIR,	// 20
	WEAR_COSTUME_SASH,	// 21
	#ifdef __WEAPON_COSTUME_SYSTEM__
	WEAR_COSTUME_WEAPON,// 22
	#endif
	WEAR_COSTUME_MOUNT,	// 	//23
#ifdef ENABLE_AURA_SYSTEM
	WEAR_COSTUME_AURA,	//24
#endif
	WEAR_RING1,			// 25
	WEAR_RING2,			// 26
	WEAR_BELT,			// 27
#ifdef ENABLE_MOUNT_COSTUME_SYSTEM
	WEAR_COSTUME_MOUNT = WEAR_RING1, // costume_mount == ring1
#endif
	#ifdef WJ_EXTENDED_PET_SYSTEM
	WEAR_PET,			// 28
	#endif
	#ifdef ENABLE_ELEMENT_SLOT
	WEAR_ELEMENT,		// 29
	#endif
#ifdef THANOS_GLOVE
	WEAR_THANOS_STONE_1,
	WEAR_THANOS_STONE_2,
	WEAR_THANOS_STONE_3,
	WEAR_THANOS_STONE_4,
	WEAR_THANOS_STONE_5,
	WEAR_THANOS_STONE_6,	//35
#endif
	WEAR_MAX = 36	// 
};

enum EDragonSoulDeckType
{
	DRAGON_SOUL_DECK_0,
	DRAGON_SOUL_DECK_1,
	DRAGON_SOUL_DECK_MAX_NUM = 2,

	DRAGON_SOUL_DECK_RESERVED_MAX_NUM = 3,	// NOTE: 중요! 아직 사용중이진 않지만, 3페이지 분량을 예약 해 둠. DS DECK을 늘릴 경우 반드시 그 수만큼 RESERVED에서 차감해야 함!
};

enum ESex
{
	SEX_MALE,
	SEX_FEMALE
};

enum EDirection
{
	DIR_NORTH,
	DIR_NORTHEAST,
	DIR_EAST,
	DIR_SOUTHEAST,
	DIR_SOUTH,
	DIR_SOUTHWEST,
	DIR_WEST,
	DIR_NORTHWEST,
	DIR_MAX_NUM
};

#define ABILITY_MAX_LEVEL	10  /* 기술 최대 레벨 */

enum EAbilityDifficulty
{
	DIFFICULTY_EASY,
	DIFFICULTY_NORMAL,
	DIFFICULTY_HARD,
	DIFFICULTY_VERY_HARD,
	DIFFICULTY_NUM_TYPES
};

enum EAbilityCategory
{
	CATEGORY_PHYSICAL,	/* 신체적 어빌리티 */
	CATEGORY_MENTAL,	/* 정신적 어빌리티 */
	CATEGORY_ATTRIBUTE,	/* 능력 어빌리티 */
	CATEGORY_NUM_TYPES
};

enum EJobs
{
	JOB_WARRIOR,
	JOB_ASSASSIN,
	JOB_SURA,
	JOB_SHAMAN,
	JOB_WOLFMAN,
	JOB_MAX_NUM
};

enum ESkillGroups
{
	SKILL_GROUP_MAX_NUM = 2,
};

enum ERaceFlags
{
	RACE_FLAG_ANIMAL	= (1 << 0),
	RACE_FLAG_UNDEAD	= (1 << 1),
	RACE_FLAG_DEVIL		= (1 << 2),
	RACE_FLAG_HUMAN		= (1 << 3),
	RACE_FLAG_ORC		= (1 << 4),
	RACE_FLAG_MILGYO	= (1 << 5),
	RACE_FLAG_INSECT	= (1 << 6),
	RACE_FLAG_FIRE		= (1 << 7),
	RACE_FLAG_ICE		= (1 << 8),
	RACE_FLAG_DESERT	= (1 << 9),
	RACE_FLAG_TREE		= (1 << 10),
	#ifdef ENABLE_ELEMENT_NEW_BONUSES
	RACE_FLAG_ELEC		= (1 << 11),
	RACE_FLAG_WIND		= (1 << 12),
	RACE_FLAG_EARTH		= (1 << 13),
	RACE_FLAG_DARK		= (1 << 14),
	RACE_FLAG_ATT_ELEC	= (1 << 15),
	RACE_FLAG_ATT_FIRE	= (1 << 16),
	RACE_FLAG_ATT_ICE	= (1 << 17),
	RACE_FLAG_ATT_WIND	= (1 << 18),
	RACE_FLAG_ATT_EARTH	= (1 << 19),
	RACE_FLAG_ATT_DARK	= (1 << 20),
	#else
	RACE_FLAG_ATT_ELEC	= (1 << 11),
	RACE_FLAG_ATT_FIRE	= (1 << 12),
	RACE_FLAG_ATT_ICE	= (1 << 13),
	RACE_FLAG_ATT_WIND	= (1 << 14),
	RACE_FLAG_ATT_EARTH	= (1 << 15),
	RACE_FLAG_ATT_DARK	= (1 << 16),
	#endif
	RACE_FLAG_METIN		= (1 << 21),
};

enum EGuildWarFlags
{
	GWAR_FLAG_DUMMY			= (1 << 0),
	GWAR_FLAG_CAN_OBSERVER	= (1 << 1),
};

enum ELoads
{
	LOAD_NONE,
	LOAD_LIGHT,
	LOAD_NORMAL,
	LOAD_HEAVY,
	LOAD_MASSIVE
};

enum
{
	QUICKSLOT_TYPE_NONE,
	QUICKSLOT_TYPE_ITEM,
	QUICKSLOT_TYPE_SKILL,
	QUICKSLOT_TYPE_COMMAND,
	QUICKSLOT_TYPE_MAX_NUM,
};

enum EParts
{
	PART_MAIN,
	PART_WEAPON,
	PART_HEAD,
	PART_HAIR,
	PART_SASH,	
	PART_AURA,	
	PART_MAX_NUM,
};

enum EChatType
{
	CHAT_TYPE_TALKING,	/* 그냥 채팅 */
	CHAT_TYPE_INFO,		/* 정보 (아이템을 집었다, 경험치를 얻었다. 등) */
	CHAT_TYPE_NOTICE,	/* 공지사항 */
	CHAT_TYPE_PARTY,	/* 파티말 */
	CHAT_TYPE_GUILD,	/* 길드말 */
	CHAT_TYPE_COMMAND,	/* 일반 명령 */
	CHAT_TYPE_SHOUT,	/* 외치기 */
	CHAT_TYPE_WHISPER,
	CHAT_TYPE_BIG_NOTICE,
	CHAT_TYPE_MONARCH_NOTICE,
	#ifdef ENABLE_DICE_SYSTEM
	CHAT_TYPE_DICE_INFO,
	#endif
	#ifdef ENABLE_TRADE_CHAT
	CHAT_TYPE_SHOUT_TRADE,
	#endif
	#ifdef ENABLE_ZODIAC_TEMPLE_CHAT
	CHAT_TYPE_ZODIAC_NOTICE,
	CHAT_TYPE_ZODIAC_SUB_NOTICE,
	CHAT_TYPE_ZODIAC_NOTICE_CLEAR,
	#endif
	CHAT_TYPE_MAX_NUM
};

enum EWhisperType
{
	WHISPER_TYPE_NORMAL		= 0,
	WHISPER_TYPE_NOT_EXIST		= 1,
	WHISPER_TYPE_TARGET_BLOCKED	= 2,
	WHISPER_TYPE_SENDER_BLOCKED	= 3,
	WHISPER_TYPE_ERROR		= 4,
	WHISPER_TYPE_GM			= 5,
	WHISPER_TYPE_SYSTEM		= 0xFF
};

enum ECharacterPosition
{
	POSITION_GENERAL,
	POSITION_BATTLE,
	POSITION_DYING,
	POSITION_SITTING_CHAIR,
	POSITION_SITTING_GROUND,
	POSITION_INTRO,
	POSITION_MAX_NUM
};

enum EGMLevels
{
	GM_PLAYER,
	GM_LOW_WIZARD,
	GM_WIZARD,
	GM_HIGH_WIZARD,
	GM_GOD,
	GM_IMPLEMENTOR
};

enum EMobRank
{
	MOB_RANK_PAWN,
	MOB_RANK_S_PAWN,
	MOB_RANK_KNIGHT,
	MOB_RANK_S_KNIGHT,
	MOB_RANK_BOSS,
	MOB_RANK_KING,
	MOB_RANK_MAX_NUM
};

enum ECharType
{
	CHAR_TYPE_MONSTER,
	CHAR_TYPE_NPC,
	CHAR_TYPE_STONE,
	CHAR_TYPE_WARP,
	CHAR_TYPE_DOOR,
	CHAR_TYPE_BUILDING,
	CHAR_TYPE_PC,
	CHAR_TYPE_POLYMORPH_PC,
	CHAR_TYPE_HORSE,
	CHAR_TYPE_GOTO
	#ifdef ENABLE_MARKET_ARAMA_SYSTEM
	,CHAR_TYPE_SHOP
	#endif
};

enum EBattleType
{
	BATTLE_TYPE_MELEE,
	BATTLE_TYPE_RANGE,
	BATTLE_TYPE_MAGIC,
	BATTLE_TYPE_SPECIAL,
	BATTLE_TYPE_POWER,
	BATTLE_TYPE_TANKER,
	BATTLE_TYPE_SUPER_POWER,
	BATTLE_TYPE_SUPER_TANKER,
	BATTLE_TYPE_MAX_NUM
};

enum EApplyTypes
{
	APPLY_NONE,
	APPLY_MAX_HP,
	APPLY_MAX_SP,
	APPLY_CON,
	APPLY_INT,
	APPLY_STR,
	APPLY_DEX,
	APPLY_ATT_SPEED,
	APPLY_MOV_SPEED,
	APPLY_CAST_SPEED,
	APPLY_HP_REGEN,
	APPLY_SP_REGEN,
	APPLY_POISON_PCT,
	APPLY_STUN_PCT,
	APPLY_SLOW_PCT,
	APPLY_CRITICAL_PCT,
	APPLY_PENETRATE_PCT,
	APPLY_ATTBONUS_HUMAN,
	APPLY_ATTBONUS_ANIMAL,
	APPLY_ATTBONUS_ORC,
	APPLY_ATTBONUS_MILGYO,
	APPLY_ATTBONUS_UNDEAD,
	APPLY_ATTBONUS_DEVIL,
	APPLY_STEAL_HP,
	APPLY_STEAL_SP,
	APPLY_MANA_BURN_PCT,
	APPLY_DAMAGE_SP_RECOVER,
	APPLY_BLOCK,
	APPLY_DODGE,
	APPLY_RESIST_SWORD,
	APPLY_RESIST_TWOHAND,
	APPLY_RESIST_DAGGER,
	APPLY_RESIST_BELL,
	APPLY_RESIST_FAN,
	APPLY_RESIST_BOW,
	APPLY_RESIST_FIRE,
	APPLY_RESIST_ELEC,
	APPLY_RESIST_MAGIC,
	APPLY_RESIST_WIND,
	APPLY_REFLECT_MELEE,
	APPLY_REFLECT_CURSE,
	APPLY_POISON_REDUCE,
	APPLY_KILL_SP_RECOVER,
	APPLY_EXP_DOUBLE_BONUS,
	APPLY_GOLD_DOUBLE_BONUS,
	APPLY_ITEM_DROP_BONUS,
	APPLY_POTION_BONUS,
	APPLY_KILL_HP_RECOVER,
	APPLY_IMMUNE_STUN,
	APPLY_IMMUNE_SLOW,
	APPLY_IMMUNE_FALL,
	APPLY_SKILL,
	APPLY_BOW_DISTANCE,
	APPLY_ATT_GRADE_BONUS,
	APPLY_DEF_GRADE_BONUS,
	APPLY_MAGIC_ATT_GRADE,
	APPLY_MAGIC_DEF_GRADE,
	APPLY_CURSE_PCT,
	APPLY_MAX_STAMINA,
	APPLY_ATTBONUS_WARRIOR,
	APPLY_ATTBONUS_ASSASSIN,
	APPLY_ATTBONUS_SURA,
	APPLY_ATTBONUS_SHAMAN,
	APPLY_ATTBONUS_MONSTER,
	APPLY_MALL_ATTBONUS,
	APPLY_MALL_DEFBONUS,
	APPLY_MALL_EXPBONUS,
	APPLY_MALL_ITEMBONUS,
	APPLY_MALL_GOLDBONUS,
	APPLY_MAX_HP_PCT,
	APPLY_MAX_SP_PCT,
	APPLY_SKILL_DAMAGE_BONUS,
	APPLY_NORMAL_HIT_DAMAGE_BONUS,
	APPLY_SKILL_DEFEND_BONUS,
	APPLY_NORMAL_HIT_DEFEND_BONUS,
	APPLY_PC_BANG_EXP_BONUS,
	APPLY_PC_BANG_DROP_BONUS,
	APPLY_EXTRACT_HP_PCT,
	APPLY_RESIST_WARRIOR,
	APPLY_RESIST_ASSASSIN,
	APPLY_RESIST_SURA,
	APPLY_RESIST_SHAMAN,
	APPLY_ENERGY,
	APPLY_DEF_GRADE,
	APPLY_COSTUME_ATTR_BONUS,
	APPLY_MAGIC_ATTBONUS_PER,
	APPLY_MELEE_MAGIC_ATTBONUS_PER,
	APPLY_RESIST_ICE,
	APPLY_RESIST_EARTH,
	APPLY_RESIST_DARK,
	APPLY_ANTI_CRITICAL_PCT,
	APPLY_ANTI_PENETRATE_PCT,
	APPLY_BLEEDING_PCT,
	APPLY_BLEEDING_REDUCE,
	APPLY_ATTBONUS_WOLFMAN,
	APPLY_RESIST_WOLFMAN,
	APPLY_RESIST_CLAW,
	#ifdef __ANTI_RESIST_MAGIC_BONUS__
	APPLY_ANTI_RESIST_MAGIC,
	#endif
	#ifdef ENABLE_ELEMENT_NEW_BONUSES
	APPLY_ATTBONUS_ELEC,
	APPLY_ATTBONUS_FIRE,
	APPLY_ATTBONUS_ICE,
	APPLY_ATTBONUS_WIND,
	APPLY_ATTBONUS_EARTH,
	APPLY_ATTBONUS_DARK,
	#endif
	APPLY_ATTBONUS_METIN,//104
	APPLY_RESIST_HUMAN,//105
	APPLY_ATTBONUS_BOSS,
	APPLY_ATTBONUS_ELEMENTS,

	MAX_APPLY_NUM,

};

enum EOnClickEvents
{
	ON_CLICK_NONE,
	ON_CLICK_SHOP,
	ON_CLICK_TALK,
	ON_CLICK_MAX_NUM
};

enum EOnIdleEvents
{
	ON_IDLE_NONE,
	ON_IDLE_GENERAL,
	ON_IDLE_MAX_NUM
};

enum EWindows
{
	RESERVED_WINDOW,
	INVENTORY,
	EQUIPMENT,
	SAFEBOX,
	MALL,
	DRAGON_SOUL_INVENTORY,
	#ifdef ENABLE_SPECIAL_STORAGE
	UPGRADE_INVENTORY,
	BOOK_INVENTORY,
	STONE_INVENTORY,
	CHEST_INVENTORY,
	ATTR_INVENTORY,
	#endif
#ifdef ENABLE_SWITCHBOT
	SWITCHBOT,
#endif
	BELT_INVENTORY,
	GROUND
};

#ifdef ENABLE_FISH_EVENT
enum EFishEventInfo
{
	FISH_EVENT_SHAPE_NONE,
	FISH_EVENT_SHAPE_1,
	FISH_EVENT_SHAPE_2,
	FISH_EVENT_SHAPE_3,
	FISH_EVENT_SHAPE_4,
	FISH_EVENT_SHAPE_5,
	FISH_EVENT_SHAPE_6,
	FISH_EVENT_SHAPE_7,
	FISH_EVENT_SHAPE_MAX_NUM,
};
#endif

enum EMobSizes
{
	MOBSIZE_RESERVED,
	MOBSIZE_SMALL,
	MOBSIZE_MEDIUM,
	MOBSIZE_BIG
};

enum EAIFlags
{
	AIFLAG_AGGRESSIVE	= (1 << 0),
	AIFLAG_NOMOVE	= (1 << 1),
	AIFLAG_COWARD	= (1 << 2),
	AIFLAG_NOATTACKSHINSU	= (1 << 3),
	AIFLAG_NOATTACKJINNO	= (1 << 4),
	AIFLAG_NOATTACKCHUNJO	= (1 << 5),
	AIFLAG_ATTACKMOB = (1 << 6 ),
	AIFLAG_BERSERK	= (1 << 7),
	AIFLAG_STONESKIN	= (1 << 8),
	AIFLAG_GODSPEED	= (1 << 9),
	AIFLAG_DEATHBLOW	= (1 << 10),
	AIFLAG_REVIVE		= (1 << 11),
};

enum EMobStatType
{
	MOB_STATTYPE_POWER,
	MOB_STATTYPE_TANKER,
	MOB_STATTYPE_SUPER_POWER,
	MOB_STATTYPE_SUPER_TANKER,
	MOB_STATTYPE_RANGE,
	MOB_STATTYPE_MAGIC,
	MOB_STATTYPE_MAX_NUM
};

enum EImmuneFlags
{
	IMMUNE_STUN		= (1 << 0),
	IMMUNE_SLOW		= (1 << 1),
	IMMUNE_FALL		= (1 << 2),
	IMMUNE_CURSE	= (1 << 3),
	IMMUNE_POISON	= (1 << 4),
	IMMUNE_TERROR	= (1 << 5),
	IMMUNE_REFLECT	= (1 << 6),
};

enum EMobEnchants
{
	MOB_ENCHANT_CURSE,
	MOB_ENCHANT_SLOW,
	MOB_ENCHANT_POISON,
	MOB_ENCHANT_STUN,
	MOB_ENCHANT_CRITICAL,
	MOB_ENCHANT_PENETRATE,
	MOB_ENCHANTS_MAX_NUM
};

enum EMobResists
{
	MOB_RESIST_SWORD,
	MOB_RESIST_TWOHAND,
	MOB_RESIST_DAGGER,
	MOB_RESIST_BELL,
	MOB_RESIST_FAN,
	MOB_RESIST_BOW,
	MOB_RESIST_FIRE,
	MOB_RESIST_ELECT,
	MOB_RESIST_MAGIC,
	MOB_RESIST_WIND,
	MOB_RESIST_POISON,
	MOB_RESIST_CLAW,
	MOB_RESISTS_MAX_NUM
};

enum
{
	SKILL_ATTR_TYPE_NORMAL = 1,
	SKILL_ATTR_TYPE_MELEE,
	SKILL_ATTR_TYPE_RANGE,
	SKILL_ATTR_TYPE_MAGIC
	/*
	   SKILL_ATTR_TYPE_FIRE,
	   SKILL_ATTR_TYPE_ICE,
	   SKILL_ATTR_TYPE_ELEC,
	   SKILL_ATTR_TYPE_DARK,
	   */
};

enum
{
	SKILL_NORMAL,
	SKILL_MASTER,
	SKILL_GRAND_MASTER,
	SKILL_PERFECT_MASTER,
#ifdef S_SKILL
	SKILL_SAGE_MASTER
#endif
};

enum EGuildWarType
{
	GUILD_WAR_TYPE_FIELD,
	GUILD_WAR_TYPE_BATTLE,
	GUILD_WAR_TYPE_FLAG,
	GUILD_WAR_TYPE_MAX_NUM
};

enum EGuildWarState
{
	GUILD_WAR_NONE,
	GUILD_WAR_SEND_DECLARE,
	GUILD_WAR_REFUSE,
	GUILD_WAR_RECV_DECLARE,
	GUILD_WAR_WAIT_START,
	GUILD_WAR_CANCEL,
	GUILD_WAR_ON_WAR,
	GUILD_WAR_END,
	GUILD_WAR_OVER,
	GUILD_WAR_RESERVE,

	GUILD_WAR_DURATION = 30*60, // 1시간
	GUILD_WAR_WIN_POINT = 1000,
	GUILD_WAR_LADDER_HALF_PENALTY_TIME = 12*60*60,
};

enum EAttributeSet 
{
	ATTRIBUTE_SET_WEAPON,
	ATTRIBUTE_SET_BODY, 
	ATTRIBUTE_SET_WRIST, 
	ATTRIBUTE_SET_FOOTS,
	ATTRIBUTE_SET_NECK,
	ATTRIBUTE_SET_HEAD,
	ATTRIBUTE_SET_SHIELD,
	ATTRIBUTE_SET_EAR,
	#ifdef ENABLE_ELEMENT_SLOT
	ATTRIBUTE_SET_ELEMENT,
	#endif
	ATTRIBUTE_SET_MAX_NUM
};

enum EPrivType
{
	PRIV_NONE,
	PRIV_ITEM_DROP,
	PRIV_GOLD_DROP,
	PRIV_GOLD10_DROP,
	PRIV_EXP_PCT,
	MAX_PRIV_NUM,
};

enum EMoneyLogType
{
	MONEY_LOG_RESERVED,
	MONEY_LOG_MONSTER,
	MONEY_LOG_SHOP,
	MONEY_LOG_REFINE,
	MONEY_LOG_QUEST,
	MONEY_LOG_GUILD,
	MONEY_LOG_MISC,
	MONEY_LOG_MONSTER_KILL,
	MONEY_LOG_DROP,
	MONEY_LOG_TYPE_MAX_NUM,
};

enum EPremiumTypes
{
	PREMIUM_EXP,		// 경험치가 1.2배
	PREMIUM_ITEM,		// 아이템 드롭율이 2배
	PREMIUM_SAFEBOX,		// 창고가 1칸에서 3칸
	PREMIUM_AUTOLOOT,		// 돈 자동 줍기
	PREMIUM_FISH_MIND,		// 고급 물고기 낚일 확률 상승
	PREMIUM_MARRIAGE_FAST,	// 금실 증가 양을 빠르게합니다.
	PREMIUM_GOLD,		// 돈 드롭율이 1.5배
	PREMIUM_MAX_NUM = 9
};

enum SPECIAL_EFFECT
{
	SE_NONE,

	SE_HPUP_RED,
	SE_SPUP_BLUE,
	SE_SPEEDUP_GREEN,
	SE_DXUP_PURPLE,
	SE_CRITICAL,
	SE_PENETRATE,
	SE_BLOCK,
	SE_DODGE,
	SE_CHINA_FIREWORK,
	SE_SPIN_TOP,
	SE_SUCCESS,
	SE_FAIL,
	SE_FR_SUCCESS,
	SE_LEVELUP_ON_14_FOR_GERMANY,
	SE_LEVELUP_UNDER_15_FOR_GERMANY,
	SE_PERCENT_DAMAGE1,
	SE_PERCENT_DAMAGE2,
	SE_PERCENT_DAMAGE3,

	SE_AUTO_HPUP,
	SE_AUTO_SPUP,

	SE_EQUIP_RAMADAN_RING,
	SE_EQUIP_HALLOWEEN_CANDY,
	SE_EQUIP_HAPPINESS_RING,
	SE_EQUIP_LOVE_PENDANT,

	#ifdef __VERSION_162__
	SE_EFFECT_HEALER,
	#endif

#ifdef ENABLE_BEVIS_SASH_SYSTEM
	SE_EFFECT_SASH_SUCCEDED,
	SE_EFFECT_SASH_EQUIP,
#endif

	SE_EQUIP_RUZGAR,
	SE_DUEL_VICTIM_EFFECT,
	SE_DUEL_KILLER_EFFECT,
	SE_DUEL_SENDER,
	SE_DUEL_RECEIVER,
	SE_DUEL_5,
	SE_DUEL_4,
	SE_DUEL_3,
	SE_DUEL_2,
	SE_DUEL_1,
	SE_DUEL_0,
	// SE_ACCE_SUCCEDED_1,
	// SE_EQUIP_ACCE_1,
	// SE_EQUIP_ACCE_2,
	// SE_EQUIP_ACCE_3,
	// SE_EQUIP_ACCE_4,

	#ifdef __MOUNT_SYSTEM__
	SE_MOUNT_1,
	SE_MOUNT_2,
	SE_MOUNT_3,
	SE_MOUNT_4,
	SE_MOUNT_5,
	SE_MOUNT_6,
	SE_MOUNT_7,
	SE_MOUNT_8,
	SE_MOUNT_9,
	SE_MOUNT_10,
	SE_MOUNT_11,
	SE_MOUNT_12,
	SE_MOUNT_13,
	SE_MOUNT_14,
	SE_MOUNT_15,
	SE_MOUNT_16,
	SE_MOUNT_17,
	SE_MOUNT_18,
	SE_MOUNT_19,
	SE_MOUNT_20,
	SE_MOUNT_21,
	SE_MOUNT_22,
	SE_MOUNT_23,
	SE_MOUNT_24,
	SE_MOUNT_25,
	SE_MOUNT_26,
	SE_MOUNT_27,
	SE_MOUNT_28,
	SE_MOUNT_29,
	SE_MOUNT_30,
	SE_MOUNT_31,
	SE_MOUNT_32,
	SE_MOUNT_33,
	SE_MOUNT_34,
	SE_MOUNT_35,
	SE_MOUNT_36,
	SE_MOUNT_37,
	SE_MOUNT_38,
	SE_MOUNT_39,
	SE_MOUNT_40,
	SE_MOUNT_41,
	SE_MOUNT_42,
	SE_MOUNT_43,
	SE_MOUNT_44,
	SE_MOUNT_45,
	SE_MOUNT_46,
	SE_MOUNT_47,
	SE_MOUNT_48,
	SE_MOUNT_49,
	SE_MOUNT_50,
	SE_MOUNT_51,
	SE_MOUNT_52,
	SE_MOUNT_53,
	SE_MOUNT_54,
	SE_MOUNT_55,
	SE_MOUNT_56,
	SE_MOUNT_57,
	SE_MOUNT_58,
	SE_MOUNT_59,
	SE_MOUNT_60,
	SE_MOUNT_61,
	#endif

	#ifdef ENABLE_ZODIAC_TEMPLE_SYSTEM
	SE_SKILL_DAMAGE_ZONE,
	SE_SKILL_DAMAGE_ZONE_BUYUK,
	SE_SKILL_DAMAGE_ZONE_ORTA,
	SE_SKILL_DAMAGE_ZONE_KUCUK,
	SE_SKILL_SAFE_ZONE,
	SE_SKILL_SAFE_ZONE_BUYUK,
	SE_SKILL_SAFE_ZONE_ORTA,
	SE_SKILL_SAFE_ZONE_KUCUK,
	SE_METEOR,
	SE_BEAD_RAIN,
	SE_FALL_ROCK,
	SE_ARROW_RAIN,
	SE_HORSE_DROP,
	SE_EGG_DROP,
	SE_DEAPO_BOOM,
	#endif
} ;

enum ETeenFlags
{
	TEENFLAG_NONE = 0,
	TEENFLAG_1HOUR,
	TEENFLAG_2HOUR,
	TEENFLAG_3HOUR,
	TEENFLAG_4HOUR,
	TEENFLAG_5HOUR,
};

#include "item_length.h"

// inventory의 position을 나타내는 구조체
// int와의 암시적 형변환이 있는 이유는,
// 인벤 관련된 모든 함수가 window_type은 받지 않고, cell 하나만 받았기 때문에,(기존에는 인벤이 하나 뿐이어서 inventory type이란게 필요없었기 때문에,)
// 인벤 관련 모든 함수 호출부분을 수정하는 것이 난감하기 떄문이다.

enum EDragonSoulRefineWindowSize
{
	DRAGON_SOUL_REFINE_GRID_MAX = 15,
};

enum EMisc2
{
	DRAGON_SOUL_EQUIP_SLOT_START = INVENTORY_MAX_NUM + WEAR_MAX_NUM,	// 180 + 32 (212)
	DRAGON_SOUL_EQUIP_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_START + (DS_SLOT_MAX * DRAGON_SOUL_DECK_MAX_NUM),	// 212 + 12 ( 224 )
	DRAGON_SOUL_EQUIP_RESERVED_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_END + (DS_SLOT_MAX * DRAGON_SOUL_DECK_RESERVED_MAX_NUM),	// 224 + 18 ( 242 )

	BELT_INVENTORY_SLOT_START = DRAGON_SOUL_EQUIP_RESERVED_SLOT_END,	// 242 
	BELT_INVENTORY_SLOT_END = BELT_INVENTORY_SLOT_START + BELT_INVENTORY_SLOT_COUNT,	// 242 + 16 ( 258 )

	INVENTORY_AND_EQUIP_SLOT_MAX = BELT_INVENTORY_SLOT_END,
};

#pragma pack(push, 1)

typedef struct SItemPos
{
	BYTE window_type;
	WORD cell;
	SItemPos ()
	{
		window_type = INVENTORY;
		cell = WORD_MAX;
	}
	SItemPos (BYTE _window_type, WORD _cell)
	{
		window_type = _window_type;
		cell = _cell;
	}
	bool IsValidItemPosition() const
	{
		switch (window_type)
		{
		case RESERVED_WINDOW:
			return false;
		case INVENTORY:
		case EQUIPMENT:
		case BELT_INVENTORY:
			return cell < INVENTORY_AND_EQUIP_SLOT_MAX;
		case DRAGON_SOUL_INVENTORY:
			return cell < (DRAGON_SOUL_INVENTORY_MAX_NUM);
		#ifdef ENABLE_SPECIAL_STORAGE
		case UPGRADE_INVENTORY:
		case BOOK_INVENTORY:
		case STONE_INVENTORY:
		case CHEST_INVENTORY:
		case ATTR_INVENTORY:
			return cell < (SPECIAL_INVENTORY_MAX_NUM);
		#endif
		case SAFEBOX:
		case MALL:
			return false;
#ifdef ENABLE_SWITCHBOT
		case SWITCHBOT:
			return cell < SWITCHBOT_SLOT_COUNT;
#endif
		default:
			return false;
		}
		return false;
	}
	bool IsEquipPosition() const
	{
		return (IsDefaultInventoryEquipPosition() || IsDragonSoulEquipPosition());
	}
	bool IsDefaultInventoryEquipPosition() const
	{
		return ((INVENTORY == window_type || EQUIPMENT == window_type) && cell >= INVENTORY_MAX_NUM && cell < INVENTORY_MAX_NUM + WEAR_MAX_NUM);
	}
#ifdef ENABLE_DS_GRADE_MYTH
	bool IsDragonSoulEquipPosition() const
	{
		return ((INVENTORY == window_type || EQUIPMENT == window_type) && cell >= DRAGON_SOUL_EQUIP_SLOT_START && cell < DRAGON_SOUL_EQUIP_SLOT_END);
	}
#else
	bool IsDragonSoulEquipPosition() const
	{
		return ((INVENTORY == window_type || EQUIPMENT == window_type) && cell >= DRAGON_SOUL_EQUIP_SLOT_START && cell < DRAGON_SOUL_EQUIP_SLOT_END);
	}
#endif
	bool IsBeltInventoryPosition() const
	{
		return ((INVENTORY == window_type) && cell >= BELT_INVENTORY_SLOT_START && cell < BELT_INVENTORY_SLOT_END);
	}
	bool IsDefaultInventoryPosition() const
	{
		return ((INVENTORY == window_type) && cell < INVENTORY_MAX_NUM);
	}
#ifdef ENABLE_SWITCHBOT
	bool IsSwitchbotPosition() const
	{
		return SWITCHBOT == window_type && cell < SWITCHBOT_SLOT_COUNT;
	}
#endif
	bool operator==(const struct SItemPos& rhs) const
	{
		return (window_type == rhs.window_type) && (cell == rhs.cell);
	}
	bool operator<(const struct SItemPos& rhs) const
	{
		return (window_type < rhs.window_type) || ((window_type == rhs.window_type) && (cell < rhs.cell));
	}
} TItemPos;

const TItemPos NPOS (RESERVED_WINDOW, WORD_MAX);

typedef enum
{
	SHOP_COIN_TYPE_GOLD, // DEFAULT VALUE
	SHOP_COIN_TYPE_SECONDARY_COIN,
#ifdef ENABLE_GEM_SYSTEM
	SHOP_COIN_TYPE_GAYA,
#endif
} EShopCoinType;

#pragma pack(pop)

#endif
